# Generated by Django 4.2.27 on 2025-12-17 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('percentage', models.PositiveIntegerField(help_text='Discount percentage (0-100)')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_total_users', models.PositiveIntegerField(blank=True, help_text='Maximum number of unique users allowed to use this coupon', null=True)),
                ('max_per_customer', models.PositiveIntegerField(blank=True, help_text='Maximum uses per customer', null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='restaurants.coupon')),
                ('order', models.ForeignKey(blank=True, help_text='Order that used this coupon (nullable for audit or pre-checkout reservations).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'indexes': [models.Index(fields=['coupon', 'user', 'created_at'], name='restaurants_coupon__6cf30c_idx'), models.Index(fields=['user', 'created_at'], name='restaurants_user_id_c816ca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='restaurants_code_70bc63_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['restaurant', 'code'], name='restaurants_restaur_42184a_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='restaurants_start_d_fb6142_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('restaurant', 'code')},
        ),
    ]
