# Generated by Django 4.2.27 on 2025-12-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_coupon_couponusage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_coupon_usage_per_order'),
        ),
    ]
