# Generated by Django 4.2.27 on 2026-01-11 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_couponusage_unique_coupon_usage_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner_user',
            field=models.ForeignKey(help_text='User who owns the restaurant.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
