# Generated by Django 4.2.27 on 2025-12-18 08:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'Mock'), ('STRIPE', 'Stripe')], default='MOCK', max_length=20)),
                ('token', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_tr_order_i_f8dfb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='payments_tr_type_93ebb9_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('MOCK', 'Mock'), ('STRIPE', 'Stripe')], default='MOCK', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('TIP', 'Tip'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order'], name='payments_tr_order_i_77e900_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status'], name='payments_tr_type_5818a6_idx'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_adcc3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'token'), name='uq_paymentmethod_user_provider_token'),
        ),
    ]
