# Generated by Django 4.2.27 on 2025-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_code_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
