# Generated by Django 4.2.27 on 2025-02-10 12:30

from django.db import migrations


def backfill_roles_and_profiles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")
    UserRole = apps.get_model("users", "UserRole")
    CustomerProfile = apps.get_model("users", "CustomerProfile")
    SellerProfile = apps.get_model("users", "SellerProfile")
    AdminProfile = apps.get_model("users", "AdminProfile")

    role_map = {
        "CUSTOMER": "customer",
        "DRIVER": "driver",
        "SELLER": "seller",
        "ADMIN": "admin",
    }

    roles = {}
    for role_name in role_map.values():
        roles[role_name], _ = Role.objects.get_or_create(name=role_name)

    for user in User.objects.all().iterator():
        legacy_role = getattr(user, "role", None)
        if not legacy_role:
            continue
        role_name = role_map.get(legacy_role)
        if not role_name:
            continue
        role = roles[role_name]
        UserRole.objects.get_or_create(user=user, role=role)

        if role_name == "customer":
            CustomerProfile.objects.get_or_create(user=user)
        elif role_name == "seller":
            SellerProfile.objects.get_or_create(user=user)
        elif role_name == "admin":
            AdminProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_roles_profiles"),
    ]

    operations = [
        migrations.RunPython(backfill_roles_and_profiles, migrations.RunPython.noop),
    ]
