# Generated by Django 4.2.27 on 2025-02-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_backfill_roles_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
