# Generated by Django 4.2.27 on 2026-01-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userrole',
            new_name='users_userr_user_id_5a6b40_idx',
            old_name='users_userro_user_id_2a2b5b_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='users_userr_role_id_fcacec_idx',
            old_name='users_userro_role_id_8b4c35_idx',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
