# Generated by Django 4.2.27 on 2025-02-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_users_userro_user_id_2a2b5b_idx_users_userr_user_id_5a6b40_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("vehicle_type", models.CharField(choices=[("BIKE", "Bike"), ("MOTOR", "Motorcycle"), ("CAR", "Car"), ("VAN", "Van")], max_length=20)),
                ("accepts_food", models.BooleanField(default=False)),
                ("accepts_shipping", models.BooleanField(default=False)),
                ("accepts_taxi", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False, help_text="Whether the driver is currently online and available for orders")),
                ("driving_license", models.FileField(blank=True, null=True, upload_to="drivers/licenses/")),
                ("id_document", models.FileField(blank=True, null=True, upload_to="drivers/ids/")),
                ("other_documents", models.FileField(blank=True, null=True, upload_to="drivers/other/")),
                ("earnings_last_month", models.DecimalField(decimal_places=2, default=0, help_text="Cached value for quick access", max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="driver_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
            },
        ),
    ]
