# Generated by Django 4.2.27 on 2026-01-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_driver_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='earnings_last_month',
        ),
    ]
