# Generated by Django 4.2.27 on 2026-01-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_restaurant_owner_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='sellers_cat_restaur_be0360_idx',
            old_name='restaurants_restaur_5aa695_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='sellers_cou_code_51209f_idx',
            old_name='restaurants_code_70bc63_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='sellers_cou_restaur_b2ea2f_idx',
            old_name='restaurants_restaur_42184a_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='sellers_cou_start_d_5e4f5f_idx',
            old_name='restaurants_start_d_fb6142_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='sellers_cou_coupon__94ba53_idx',
            old_name='restaurants_coupon__6cf30c_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='sellers_cou_user_id_7c173a_idx',
            old_name='restaurants_user_id_c816ca_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='sellers_ite_restaur_0288b9_idx',
            old_name='restaurants_restaur_5407de_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='sellers_ite_restaur_60f0bb_idx',
            old_name='restaurants_restaur_bf45d2_idx',
        ),
    ]
