# Generated by Django 4.2.27 on 2025-02-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0004_alter_restaurant_owner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
