# Generated by Django 4.2.27 on 2026-01-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_rename_restaurants_restaur_5aa695_idx_sellers_cat_restaur_be0360_idx_and_more'),
        ('sellers', '0005_restaurant_logo'),
    ]

    operations = [
    ]
