# Generated by Django 4.2.27 on 2025-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the driver is currently online and available for orders'),
        ),
    ]
