# Generated by Django 4.2.27 on 2025-12-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0002_driverprofile_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_verifications', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Verification',
                'verbose_name_plural': 'Driver Verifications',
                'indexes': [models.Index(fields=['driver', 'created_at'], name='drivers_dri_driver__9fbb66_idx')],
            },
        ),
    ]
