# Generated by Django 4.2.27 on 2025-02-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_driververification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverProfile",
        ),
    ]
