# Generated by Django 4.2.27 on 2025-12-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
        ('users', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('FOOD', 'Food'), ('SHIPPING', 'Shipping'), ('TAXI', 'Taxi')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SEARCHING_FOR_DRIVER', 'Searching for driver'), ('DRIVER_NOTIFICATION_SENT', 'Driver notification sent'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculated_distance', models.DecimalField(blank=True, decimal_places=3, help_text='Distance in km (or your chosen unit) calculated by pricing engine', max_digits=10, null=True)),
                ('calculated_time', models.PositiveIntegerField(blank=True, help_text='Estimated time in seconds (or your chosen unit) calculated by pricing engine', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
                ('dropoff_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_orders', to='users.address')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='users.address')),
                ('restaurant', models.ForeignKey(blank=True, help_text='Food orders only; null for shipping/taxi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ShippingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('content', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_package', to='orders.order')),
            ],
            options={
                'verbose_name': 'Shipping Package',
                'verbose_name_plural': 'Shipping Packages',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SEARCHING_FOR_DRIVER', 'Searching for driver'), ('DRIVER_NOTIFICATION_SENT', 'Driver notification sent'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status History',
                'indexes': [models.Index(fields=['order', 'timestamp'], name='orders_orde_order_i_09d470_idx'), models.Index(fields=['status', 'timestamp'], name='orders_orde_status_859939_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customizations', models.JSONField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurants.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderDriverSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_at_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_suggestions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_suggestions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Driver Suggestion',
                'verbose_name_plural': 'Order Driver Suggestions',
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_c56d12_idx'), models.Index(fields=['driver', 'created_at'], name='orders_orde_driver__53b6cb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status', 'created_at'], name='orders_orde_order_t_09eddf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='orders_orde_custome_242823_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver', 'created_at'], name='orders_orde_driver__3f274f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'created_at'], name='orders_orde_restaur_763bf4_idx'),
        ),
    ]
