# Generated by Django 4.2.27 on 2025-12-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied (e.g. via coupon).', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total before discounts (baseline for coupon calculation).', max_digits=10, null=True),
        ),
    ]
