# Generated by Django 4.2.27 on 2025-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_requested_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_delivery_type',
            field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('MOTOR', 'Motorcycle'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=20, null=True),
        ),
    ]
