# Generated by Django 4.2.27 on 2025-12-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_order_requested_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_form_data', models.JSONField(help_text='Raw scanned payload from seller app (manual order form).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_order_record', to='orders.order')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Order',
                'verbose_name_plural': 'Manual Orders',
                'indexes': [models.Index(fields=['staff_user', 'created_at'], name='orders_manu_staff_u_d0277e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('filter_params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export',
                'verbose_name_plural': 'Exports',
                'indexes': [models.Index(fields=['admin', 'created_at'], name='orders_expo_admin_i_f926ed_idx')],
            },
        ),
    ]
