# Generated by Django 4.2.27 on 2026-01-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_manualorder_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDispatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField(default=0)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Dispatch State',
                'verbose_name_plural': 'Order Dispatch States',
            },
        ),
        migrations.AddField(
            model_name='orderdriversuggestion',
            name='cycle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdriversuggestion',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdriversuggestion',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdriversuggestion',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdriversuggestion',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderdriversuggestion',
            index=models.Index(fields=['order', 'status', 'created_at'], name='orders_orde_order_i_94d914_idx'),
        ),
        migrations.AddField(
            model_name='orderdispatchstate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_state', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='orderdispatchstate',
            index=models.Index(fields=['is_active', 'next_retry_at'], name='orders_orde_is_acti_2c70e1_idx'),
        ),
    ]
