# Generated by Django 4.2.27 on 2026-01-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderdispatchstate_orderdriversuggestion_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
