"""
Django settings for taybat_backend project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
try:
    from celery.schedules import schedule
except ImportError:  # pragma: no cover - optional for non-celery environments
    schedule = None

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!

SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure")
DEBUG = os.getenv("DEBUG", "0") == "1"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com"]

# Application definition

INSTALLED_APPS = [
    "admin_tools",
    "admin_tools.theming",
    "admin_tools.menu",
    "admin_tools.dashboard",
    "django_plotly_dash.apps.DjangoPlotlyDashConfig",
    "dpd_static_support",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # my apps
    'users',
    'drivers',
    'sellers',
    'orders',
    'payments',
    'loyalty',
    'notifications',
    'config',
    # Third-party apps
    "drf_spectacular",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django_plotly_dash.middleware.BaseMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True # TODO: adjust for production
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'taybat_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,
        'OPTIONS': {
            "loaders": [
                "admin_tools.template_loaders.Loader",
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ADMIN_TOOLS_INDEX_DASHBOARD = "config.admin_dashboard.CustomIndexDashboard"

WSGI_APPLICATION = 'taybat_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "django_plotly_dash.finders.DashAssetFinder",
    "django_plotly_dash.finders.DashComponentFinder",
    "django_plotly_dash.finders.DashAppDirectoryFinder",
]

PLOTLY_DASH = {
    "serve_locally": True,
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=500), # ToDO: adjust for production
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

OTP_CODE_TTL_SECONDS = 300
OTP_CODE_LENGTH = 6

CSRF_TRUSTED_ORIGINS = [
    'chrome-extension://ehafadccdcdedbhcbddihehiodgcddpl',
]

SPECTACULAR_SETTINGS = {
    "TITLE": "Taybat API",
    "DESCRIPTION": "Backend API for Taybat (Food, Taxi, Shipping).",
    "VERSION": "1.0.0",
    # Optional but recommended:
    "SERVE_INCLUDE_SCHEMA": True,
    "ENUM_NAME_OVERRIDES": {
        "OrderStatusEnum": "orders.models.ORDER_STATUS_CHOICES",
        "RestaurantStatusEnum": "sellers.models.RESTAURANT_STATUS_CHOICES",
        "TransactionStatusEnum": "payments.models.TRANSACTION_STATUS_CHOICES",
        "DriverStatusEnum": "users.models.DRIVER_STATUS_CHOICES",
        "OrderDriverSuggestionStatusEnum": "orders.models.ORDER_DRIVER_SUGGESTION_STATUS_CHOICES",
        "VehicleTypeEnum": "orders.models.VEHICLE_TYPE_CHOICES",
    },
}
# Dispatch settings
DISPATCH_MATCH_INTERVAL_SECONDS = int(os.getenv("DISPATCH_MATCH_INTERVAL_SECONDS", "10"))
DISPATCH_ACCEPTANCE_WINDOW_SECONDS = int(os.getenv("DISPATCH_ACCEPTANCE_WINDOW_SECONDS", "60"))
DISPATCH_SUGGESTION_LIMIT = int(os.getenv("DISPATCH_SUGGESTION_LIMIT", "5"))
DISPATCH_MAX_CYCLES = int(os.getenv("DISPATCH_MAX_CYCLES", "5"))
DISPATCH_RETRY_DELAY_SECONDS = int(os.getenv("DISPATCH_RETRY_DELAY_SECONDS", "10"))
DISPATCH_LOCATION_STALE_SECONDS = int(os.getenv("DISPATCH_LOCATION_STALE_SECONDS", "60"))

CELERY_BEAT_SCHEDULE = (
    {
        "dispatch-match-loop": {
            "task": "orders.tasks.dispatch_match_loop",
            "schedule": schedule(DISPATCH_MATCH_INTERVAL_SECONDS),
        },
    }
    if schedule
    else {}
)
# settings.py
LOYALTY_POINTS_PER_EUR = 1
LOYALTY_ONLY_FOOD = False
LOYALTY_ISSUE_ON_STATUS = "COMPLETED"


import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    integrations=[DjangoIntegration()],
    traces_sample_rate=0.1,  # start low
    send_default_pii=True,   # if you want user info
    environment=os.getenv("SENTRY_ENVIRONMENT", "development")
)
