# Generated by Django 4.2.27 on 2026-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_bb3bdf_idx'),
        ),
    ]
