# Generated by Django 4.2.27 on 2026-01-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_f39341_idx',
            old_name='notificatio_recipie_7c878a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_86ea8b_idx',
            old_name='notificatio_recipie_0c8b0d_idx',
        ),
    ]
